import type { HarpStrata } from '../types'
import { EXAMPLE_PITCH_MATRICES } from '../Pitch/testResources'
import { EXAMPLE_DEGREE_MATRICES } from '../Degree/testResources'
import { MAJOR_DIATONIC_APPARATUS } from '../Apparatus/constants'

const C_MAJOR_DIATONIC_FIRST_POZITION: HarpStrata = {
  apparatus: MAJOR_DIATONIC_APPARATUS,
  degreeMatrix: EXAMPLE_DEGREE_MATRICES.MAJOR_DIATONIC_FIRST_POZITION,
  pitchMatrix: EXAMPLE_PITCH_MATRICES.MAJOR_DIATONIC_C_HARMONICA,
} as const

const C_MAJOR_DIATONIC_SECOND_POZITION: HarpStrata = {
  apparatus: MAJOR_DIATONIC_APPARATUS,
  degreeMatrix: EXAMPLE_DEGREE_MATRICES.MAJOR_DIATONIC_SECOND_POZITION,
  pitchMatrix: EXAMPLE_PITCH_MATRICES.MAJOR_DIATONIC_C_HARMONICA,
} as const

export const EXAMPLE_STRATA: {
  C_MAJOR_DIATONIC_FIRST_POZITION: HarpStrata;
  C_MAJOR_DIATONIC_SECOND_POZITION: HarpStrata;
} = {
  C_MAJOR_DIATONIC_FIRST_POZITION,
  C_MAJOR_DIATONIC_SECOND_POZITION,
} as const
