export { deriveViewableMatrix } from './derive-viewablematrix'
export { deriveColumnBounds } from './derive-columnbounds'
export { deriveLayoutFacts } from './derive-layoutfacts'
export { setFromHarpStrataToTuningId } from './setfrom-harpstrata-to-tuningid'
export { setFromHarpStrataToActiveDegreeIds } from './setfrom-harpstrata-to-activedegreeids'
export { setFromHarpStrataToActivePitchIds } from './setfrom-harpstrata-to-activepitchids'
